Settings overhaul 2
samvera/hyku pull request #1749
Opened 2021-09-14 00:49 UTC by orangewolf

Ref #1719 

Most of the credit for this work goes to Ubiquity Press. Many of the lines here are extracted from https://github.com/ubiquitypress/hyku_addons

This development was funded by the British Library: https://bl.iro.bl.uk

Part 2 of settings overhaul #1746 . This work is focuses on making all the settings either functional or marking them as disabled.  This was done to keep compatibility with the existing Ubiquity data layout. 

This PR will focus on the follwing
- Port or discard implementations of existing settings
- Align all existing settings and remove the Settings class
- Set defaults based on Hyrax env var names

Admin interface will be a seperate PR.

@samvera/hyku-code-reviewers

2021-09-17 20:00 UTC, orangewolf commented on app/models/concerns/account_settings.rb
> +    setting :bulkrax_validations, type: 'boolean', disabled: true
disabled here doesn't _do_ anything yet. it just identifies those setting that Hyku doesn't use at the moment. Most of these are things that are in hyku_addons or other places but haven't made it in to hyku yet.  I'm designating them so I can skip them in the UI until they are doing something.

2021-09-17 21:32 UTC, chauncey-garrett requested changes

2021-09-17 21:32 UTC, chauncey-garrett commented on README.md
> +To enable single tenant, set `HYKU_MULTITANT=false` in your `docker-compose.yml` and `docker-compose.production.yml` configs. After changinig this setting, run `rails db:seed` to prepopulate the sing
`HYKU_MULTITENANT`

(spelling)

2021-09-18 07:06 UTC, orangewolf commented on README.md
> +To enable single tenant, set `HYKU_MULTITANT=false` in your `docker-compose.yml` and `docker-compose.production.yml` configs. After changinig this setting, run `rails db:seed` to prepopulate the sing
thank you!

2022-01-03 07:05 UTC, orangewolf commented
moved to #1771

2022-01-03 07:05 UTC, closed without merging