Moving ContentBlock methods
samvera/hyku pull request #1853
Opened 2022-11-30 20:37 UTC by jeremyf

Prior to this commit there were two very similar chunks of code regarding `ContentBlock.block_for` type logic.

With this commit, those chunks of code are consolidated.

Why the consolidation?  There's an opportunity to more aggressively cache those values.

At present, looking at the logs there are numerous singular queries of the ContentBlock structure.  (See the details block below)

Through this consolidation we can now more
easily introduce a caching and invalidation layer.

One possible caching mechanism would be on initial query to load all named blocks into an in memory array; then when we update the block we invalidate the in-memory array.

The present logging does not provide insight into the cost of each of those individual queries but that is a lot of query calls (which ActiveRecord caches).

<details>
<summary>Content Blog Log Query</summary>

```
ContentBlock Load (0.6ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "body_font"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.1ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "body_font"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "body_font"], ["LIMIT", 1]]
ContentBlock Load (0.3ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "headline_font"], ["LIMIT", 1]]
ContentBlock Load (0.2ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "link_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "link_color"], ["LIMIT", 1]]
ContentBlock Load (0.2ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "link_hover_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "link_color"], ["LIMIT", 1]]
ContentBlock Load (0.2ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "footer_link_color"], ["LIMIT", 1]]
ContentBlock Load (0.2ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "footer_link_hover_color"], ["LIMIT", 1]]
ContentBlock Load (0.2ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "header_background_color"], ["LIMIT", 1]]
ContentBlock Load (0.2ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "header_text_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "header_background_color"], ["LIMIT", 1]]
ContentBlock Load (0.2ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "searchbar_background_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "searchbar_background_color"], ["LIMIT", 1]]
ContentBlock Load (0.2ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "searchbar_text_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "searchbar_text_color"], ["LIMIT", 1]]
ContentBlock Load (0.2ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "searchbar_background_hover_color"], ["LIMIT", 1]]
ContentBlock Load (0.2ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "searchbar_text_hover_color"], ["LIMIT", 1]]
ContentBlock Load (0.2ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "active_tabs_background_color"], ["LIMIT", 1]]
ContentBlock Load (0.2ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "primary_button_background_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "primary_button_background_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "primary_button_background_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "primary_button_background_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "primary_button_background_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "primary_button_background_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "primary_button_background_color"], ["LIMIT", 1]]
ContentBlock Load (0.6ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "default_button_background_color"], ["LIMIT", 1]]
ContentBlock Load (0.3ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "default_button_border_color"], ["LIMIT", 1]]
ContentBlock Load (0.3ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "default_button_text_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "default_button_background_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "default_button_border_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "default_button_background_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "default_button_border_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "default_button_background_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "default_button_border_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "default_button_background_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "default_button_border_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "default_button_background_color"], ["LIMIT", 1]]
CACHE ContentBlock Load (0.0ms)  SELECT  "content_blocks".* FROM "content_blocks" WHERE "content_blocks"."name" = $1 LIMIT $2  [["name", "default_button_border_color"], ["LIMIT", 1]]
ContentBlock Load (0.3ms)  SELEC [...]

2022-11-30 22:30 UTC, kirkkwang requested changes
just the one extra space

2022-11-30 22:30 UTC, kirkkwang commented on spec/models/content_block_spec.rb
> +    let(:block_name) {  "blocky.mc.blockface" }
Remove extra space
```rb
let(:block_name) { "blocky.mc.blockface" }
```
looks like this getting flagged in CI

2022-12-01 23:46 UTC, kirkkwang submitted a review, later dismissed

2022-12-14 18:06 UTC, laritakr approved these changes

2022-12-14 18:54 UTC, merged