Update FileSetDerivatives override
samvera/hyku pull request #1924
Opened 2023-02-25 15:42 UTC by kirkkwang

`FileSetDerivatives` used the `#class_eval` method of overriding.  We have since favored the decorator pattern instead.  This commit will also add a test for `CreateDerivativesJob` and a couple of new fixtures to make sure we are getting the thumbnail sizes.

2023-04-12 16:22 UTC, alishaevn commented on app/services/hyrax/file_set_derivatives_service_decorator.rb
> +# OVERRIDE: increase size of thumbnails for better viewing in Neutral theme home page
```suggestion
# OVERRIDE: Hyrax v2.9.0 to increase size of thumbnails for better viewing in Neutral theme home page
```

2023-04-25 13:28 UTC, alishaevn requested changes

2023-06-23 23:51 UTC, orangewolf approved these changes

2024-08-20 00:46 UTC, kirkkwang commented
Change already made

2024-08-20 00:46 UTC, closed without merging